name: Redshift-Serverless-CostInfo-to-Cluster

on:
  # schedule:
  # - cron: "50 23 * * SUN"  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install boto3
           pip install pytz

    - name: Execute Python script
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: |
        cd Experian/Jenkins/RedshiftServerlessAutomation/
        python redshift_serverless_costInfo_to_cluster.py
